### ISSUE TITLE
Integrate GGP hackpatches for public builds

### ISSUE THREAD

**Issue by flibitijibibo** [cybik/angle-bootstraps#5]
The following patches need to be applied to the ANGLE source after everything has been downloaded:

ANGLE: https://github.com/ANGLE-Builds/angle-ggp/commit/ce66f841f114f7f1b124733a9c626cb9f1af2fa7
Vulkan-Loader: https://github.com/ANGLE-Builds/Vulkan-Loader/commit/6080bcfd4aa3f361e2217eec6a7f43fd12455692

With these patches in place, it should be possible to build ANGLE GGP from the upstream repository, after this commit has been reviewed:

https://github.com/KhronosGroup/Vulkan-Headers/pull/90

**Comment by cybik** [comment]
Writing a patch step to apply the needful for GGP builds through confstrap should be enough.

**Comment by flibitijibibo** [comment]
Right as GitHub Actions died I was able to confirm that applying the above changes as patches works fine. We can remove the Vulkan-Headers patch once that's merged officially.
