### ISSUE TITLE
Upload Linux artifacts as tarball

### ISSUE THREAD

**Issue by flibitijibibo** [cybik/angle-bootstraps#6]
In the Linux action, we produce a tarball...

https://github.com/cybik/angle-bootstraps/blob/master/.github/workflows/linux.yml#L53

... but the artifact that gets uploaded is a totally separate zip file. We should upload a tar instead, so we can preserve the `libGLESv2.so -> libGLESv2.so.2` symlink.

**Comment by cybik** [comment]
I'll restore archiving the tarball then. I had removed it because it was doing a double-compression. Sorry for that.

**Comment by cybik** [comment]
https://github.com/cybik/angle-bootstraps/commit/d5a2a3f8456175b087f3e7b2d8498a787a42a11e should fill the requirement.
